name: EXPManager
version: '1.0-SNAPSHOT'
main: org.ts2.expmanager.EXPManager
api-version: '1.20'
authors: [TS2_YouGame]
depend: [CommandAPI]

commands:
#  setmaxlvl:
#    usage: "/setmaxlvl <nick owner> <level> - set max lvl"
#    aliases:
#      - setmaxlvl
#      - sml

permissions:
  expmanager.setmaxlvl:
    description: set max lvl
    default: op